del /s *.o
del /s *.crf
del /s *.d
del /s *.lst
del /s *.dep
del /s *.tilz0R
del /s *.map
del /s *.lnp
del /s *.iex
del /s *.mk
del /s *.elf
del /s *.list
del /s *.bak
del /s *.axf
del /s *.cur*
del /s *.user*
del /s JLinkLog.txt
del /s main.htm
del /s main.build_log.htm